#include "my_vulkan.h"
#include "../../ch02/0201_allocator.h"
#include <stddef.h>
#include <iostream>
#include <stdlib.h>
VkInstance m_instance = VK_NULL_HANDLE;
VkPhysicalDevice m_physicalDevice = VK_NULL_HANDLE;
VkPhysicalDevice *m_devices = nullptr;
VkDevice m_device = VK_NULL_HANDLE;
VkQueue m_queue = VK_NULL_HANDLE;
std::vector<vk_buffer> m_buffers;
int device_count = 0;
vk_image m_colorImage;
vk_render_pass m_renderPass;
vk_framebuffer m_framebuffer;
vk_pipeline m_pipeline;
static vk_allocator g_bufferAllocator;
static const VkAllocationCallbacks g_bufferAllocCallbacks = g_bufferAllocator;
static vk_allocator g_imageAllocator;
static const VkAllocationCallbacks g_imageAllocCallbacks = g_imageAllocator;
size_t count_enabled_features(const VkPhysicalDeviceFeatures *features) { const VkBool32 *p = (const VkBool32 *)features; size_t count = 0; for (size_t i = 0; i < sizeof(VkPhysicalDeviceFeatures) / sizeof(VkBool32); ++i) if (p[i]) ++count; return count; }
static uint32_t find_memory_type(uint32_t typeFilter, VkMemoryPropertyFlags properties) { VkPhysicalDeviceMemoryProperties memProperties; vkGetPhysicalDeviceMemoryProperties(m_physicalDevice, &memProperties); for (uint32_t i = 0; i < memProperties.memoryTypeCount; ++i) if ((typeFilter & (1u << i)) && (memProperties.memoryTypes[i].propertyFlags & properties) == properties) return i; return UINT32_MAX; }
VkResult vk_device_init_count(int *count) { *count = 0; VkApplicationInfo appInfo = {VK_STRUCTURE_TYPE_APPLICATION_INFO, nullptr, nullptr, 0, nullptr, 0, VK_API_VERSION_1_0}; const char* validationLayers[] = {"VK_LAYER_KHRONOS_validation"}; VkInstanceCreateInfo instanceCreateInfo = {VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO, nullptr, 0, &appInfo, 1, validationLayers, 0, nullptr}; VkResult result = vkCreateInstance(&instanceCreateInfo, nullptr, &m_instance); if (result != VK_SUCCESS) return VK_ERROR_INITIALIZATION_FAILED; uint32_t physicalDevCount = 0; result = vkEnumeratePhysicalDevices(m_instance, &physicalDevCount, nullptr); if (result != VK_SUCCESS || physicalDevCount == 0) return VK_ERROR_INITIALIZATION_FAILED; m_devices = (VkPhysicalDevice*)malloc(sizeof(VkPhysicalDevice) * physicalDevCount); if (m_devices != nullptr) { vkEnumeratePhysicalDevices(m_instance, &physicalDevCount, &m_devices[0]); *count = (int)physicalDevCount; } return result; }
VkResult vk_get_device_properties(int deviceIndex, uint32_t *queueFamilyPropertyCount) { if(queueFamilyPropertyCount == nullptr || deviceIndex < 0 || device_count <= deviceIndex) return VK_ERROR_INITIALIZATION_FAILED; vkGetPhysicalDeviceQueueFamilyProperties(m_devices[deviceIndex], queueFamilyPropertyCount, nullptr); return *queueFamilyPropertyCount > 0 ? VK_SUCCESS : VK_ERROR_INITIALIZATION_FAILED; }
VkResult vk_get_logical_device(int device_index, int *feature_count) { if(device_index < 0 || device_index >= device_count) return VK_ERROR_INITIALIZATION_FAILED; VkPhysicalDeviceFeatures supportedFeatures = {}, requiredFeatures = {}; vkGetPhysicalDeviceFeatures(m_devices[device_index], &supportedFeatures); const float queuePriority = 1.0f; const VkDeviceQueueCreateInfo deviceQueueCreateInfo = {VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO, nullptr, 0, 0, 1, &queuePriority}; *feature_count = (int)count_enabled_features(&supportedFeatures); const VkDeviceCreateInfo deviceCreateInfo = {VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO, nullptr, 0, 1, &deviceQueueCreateInfo, 0, nullptr, 0, nullptr, &requiredFeatures}; VkResult result = vkCreateDevice(m_devices[device_index], &deviceCreateInfo, nullptr, &m_device); if (result != VK_SUCCESS) return VK_ERROR_INITIALIZATION_FAILED; m_physicalDevice = m_devices[device_index]; vkGetDeviceQueue(m_device, 0, 0, &m_queue); return VK_SUCCESS; }
VkResult vk_create_image(uint32_t width, uint32_t height, VkFormat format, VkImageUsageFlags usage, vk_image *outImage) { if (m_device == VK_NULL_HANDLE || outImage == nullptr) return VK_ERROR_INITIALIZATION_FAILED; const VkImageCreateInfo imageCreateInfo = {VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO, nullptr, 0, VK_IMAGE_TYPE_2D, format, {width, height, 1}, 1, 1, VK_SAMPLE_COUNT_1_BIT, VK_IMAGE_TILING_OPTIMAL, usage, VK_SHARING_MODE_EXCLUSIVE, 0, nullptr, VK_IMAGE_LAYOUT_UNDEFINED}; VkResult vkr = vkCreateImage(m_device, &imageCreateInfo, &g_imageAllocCallbacks, &outImage->handle); if (vkr != VK_SUCCESS) return VK_ERROR_INITIALIZATION_FAILED; outImage->format = format; outImage->width = width; outImage->height = height; return vkr; }
VkResult vk_track_image(vk_image *image, uint32_t width, uint32_t height, VkFormat format, VkMemoryPropertyFlags properties) { VkResult vkr = VK_INCOMPLETE; if (m_device == VK_NULL_HANDLE || image == nullptr) return VK_ERROR_INITIALIZATION_FAILED; VkMemoryRequirements memRequirements; vkGetImageMemoryRequirements(m_device, image->handle, &memRequirements); uint32_t memoryTypeIndex = find_memory_type(memRequirements.memoryTypeBits, properties); if (memoryTypeIndex == UINT32_MAX) { vkr = VK_ERROR_INITIALIZATION_FAILED; goto destroy_image; } { const VkMemoryAllocateInfo allocInfo = {VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO, nullptr, memRequirements.size, memoryTypeIndex}; vkr = vkAllocateMemory(m_device, &allocInfo, &g_imageAllocCallbacks, &image->memory); if (vkr != VK_SUCCESS) { vkr = VK_ERROR_OUT_OF_DEVICE_MEMORY; goto destroy_image; } } vkr = vkBindImageMemory(m_device, image->handle, image->memory, 0); if (vkr != VK_SUCCESS) { vkr = VK_ERROR_OUT_OF_DEVICE_MEMORY; goto free_memory; } image->format = format; image->width = width; image->height = height; return vkr; free_memory: vkFreeMemory(m_device, image->memory, &g_imageAllocCallbacks); image->memory = VK_NULL_HANDLE; destroy_image: vkDestroyImage(m_device, image->handle, &g_imageAllocCallbacks); image->handle = VK_NULL_HANDLE; return vkr; }
VkResult vk_create_shader_module(const std::vector<char> *spvCode, VkShaderModule *outModule) { if (m_device == VK_NULL_HANDLE || spvCode == nullptr) return VK_ERROR_INITIALIZATION_FAILED; const VkShaderModuleCreateInfo createInfo = {VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO, nullptr, 0, spvCode->size(), (const uint32_t*)spvCode->data()}; VkResult vkr = vkCreateShaderModule(m_device, &createInfo, &g_bufferAllocCallbacks, outModule); return vkr != VK_SUCCESS ? VK_ERROR_INITIALIZATION_FAILED : vkr; }
VkResult vk_create_render_pass(VkFormat colorFormat, vk_render_pass *outRenderPass) { if (m_device == VK_NULL_HANDLE || outRenderPass == nullptr) return VK_ERROR_INITIALIZATION_FAILED; const VkAttachmentDescription colorAttachment = {0, colorFormat, VK_SAMPLE_COUNT_1_BIT, VK_ATTACHMENT_LOAD_OP_CLEAR, VK_ATTACHMENT_STORE_OP_STORE, VK_ATTACHMENT_LOAD_OP_DONT_CARE, VK_ATTACHMENT_STORE_OP_DONT_CARE, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL}; const VkAttachmentReference colorAttachmentRef = {0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL}; const VkSubpassDescription subpass = {0, VK_PIPELINE_BIND_POINT_GRAPHICS, 0, nullptr, 1, &colorAttachmentRef, nullptr, nullptr, 0, nullptr}; const VkRenderPassCreateInfo renderPassInfo = {VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO, nullptr, 0, 1, &colorAttachment, 1, &subpass, 0, nullptr}; VkResult vkr = vkCreateRenderPass(m_device, &renderPassInfo, &g_bufferAllocCallbacks, &outRenderPass->handle); return vkr != VK_SUCCESS ? VK_ERROR_INITIALIZATION_FAILED : vkr; }
VkResult vk_create_framebuffer(vk_image *colorImage, vk_render_pass *renderPass, vk_framebuffer *outFramebuffer) { if (m_device == VK_NULL_HANDLE || colorImage == nullptr || renderPass == nullptr) return VK_ERROR_INITIALIZATION_FAILED; VkImageView colorView; const VkImageViewCreateInfo viewCreateInfo = {VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO, nullptr, 0, colorImage->handle, VK_IMAGE_VIEW_TYPE_2D, colorImage->format, {VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY}, {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1}}; VkResult vkr = vkCreateImageView(m_device, &viewCreateInfo, &g_imageAllocCallbacks, &colorView); if (vkr != VK_SUCCESS) return VK_ERROR_INITIALIZATION_FAILED; const VkFramebufferCreateInfo framebufferInfo = {VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO, nullptr, 0, renderPass->handle, 1, &colorView, colorImage->width, colorImage->height, 1}; vkr = vkCreateFramebuffer(m_device, &framebufferInfo, &g_bufferAllocCallbacks, &outFramebuffer->handle); vkDestroyImageView(m_device, colorView, &g_imageAllocCallbacks); return vkr != VK_SUCCESS ? VK_ERROR_INITIALIZATION_FAILED : vkr; }
VkResult vk_create_pipeline(VkShaderModule vertShader, VkShaderModule fragShader, vk_render_pass *renderPass, vk_pipeline *outPipeline) { if (m_device == VK_NULL_HANDLE || renderPass == nullptr) return VK_ERROR_INITIALIZATION_FAILED; const VkPipelineShaderStageCreateInfo shaderStages[2] = {{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, nullptr, 0, VK_SHADER_STAGE_VERTEX_BIT, vertShader, "main", nullptr}, {VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, nullptr, 0, VK_SHADER_STAGE_FRAGMENT_BIT, fragShader, "main", nullptr}}; const VkPipelineVertexInputStateCreateInfo vertexInputInfo = {VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO, nullptr, 0, 0, nullptr, 0, nullptr}; const VkPipelineInputAssemblyStateCreateInfo inputAssembly = {VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO, nullptr, 0, VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, VK_FALSE}; const VkViewport viewport = {0.0f, 0.0f, 800.0f, 600.0f, 0.0f, 1.0f}; const VkRect2D scissor = {{0, 0}, {800, 600}}; const VkPipelineViewportStateCreateInfo viewportState = {VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO, nullptr, 0, 1, &viewport, 1, &scissor}; const VkPipelineRasterizationStateCreateInfo rasterizer = {VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO, nullptr, 0, VK_FALSE, VK_FALSE, VK_POLYGON_MODE_FILL, VK_CULL_MODE_BACK_BIT, VK_FRONT_FACE_CLOCKWISE, VK_FALSE, 0.0f, 0.0f, 0.0f, 1.0f}; const VkPipelineMultisampleStateCreateInfo multisampling = {VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO, nullptr, 0, VK_SAMPLE_COUNT_1_BIT, VK_FALSE, 1.0f, nullptr, VK_FALSE, VK_FALSE}; const VkPipelineColorBlendAttachmentState colorBlendAttachment = {VK_FALSE, VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ZERO, VK_BLEND_OP_ADD, VK_BLEND_FACTOR_ONE, VK_BLEND_FACTOR_ZERO, VK_BLEND_OP_ADD, VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT}; const VkPipelineColorBlendStateCreateInfo colorBlending = {VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO, nullptr, 0, VK_FALSE, VK_LOGIC_OP_COPY, 1, &colorBlendAttachment, {0.0f, 0.0f, 0.0f, 0.0f}}; const VkPipelineLayoutCreateInfo pipelineLayoutInfo = {VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO, nullptr, 0, 0, nullptr, 0, nullptr}; VkResult vkr = vkCreatePipelineLayout(m_device, &pipelineLayoutInfo, &g_bufferAllocCallbacks, &outPipeline->layout); if (vkr != VK_SUCCESS) return VK_ERROR_INITIALIZATION_FAILED; const VkGraphicsPipelineCreateInfo pipelineInfo = {VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO, nullptr, 0, 2, shaderStages, &vertexInputInfo, &inputAssembly, nullptr, &viewportState, &rasterizer, &multisampling, nullptr, &colorBlending, nullptr, outPipeline->layout, renderPass->handle, 0, VK_NULL_HANDLE, -1}; vkr = vkCreateGraphicsPipelines(m_device, VK_NULL_HANDLE, 1, &pipelineInfo, &g_bufferAllocCallbacks, &outPipeline->handle); return vkr != VK_SUCCESS ? VK_ERROR_INITIALIZATION_FAILED : vkr; }
VkResult vk_create_buffer(VkDeviceSize size, VkBufferUsageFlags usage, vk_buffer *outBuffer) { if (m_device == VK_NULL_HANDLE || outBuffer == nullptr) return VK_ERROR_INITIALIZATION_FAILED; const VkBufferCreateInfo bufferCreateInfo = {VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO, nullptr, 0, size, usage, VK_SHARING_MODE_EXCLUSIVE, 0, nullptr}; VkResult vkr = vkCreateBuffer(m_device, &bufferCreateInfo, &g_bufferAllocCallbacks, &outBuffer->handle); if (vkr != VK_SUCCESS) return VK_ERROR_INITIALIZATION_FAILED; outBuffer->size = size; return vkr; }
VkResult vk_track_buffer(vk_buffer *buffer, VkDeviceSize size, VkMemoryPropertyFlags properties) { VkResult vkr = VK_INCOMPLETE; if (m_device == VK_NULL_HANDLE || buffer == nullptr) return VK_ERROR_INITIALIZATION_FAILED; VkMemoryRequirements memRequirements; vkGetBufferMemoryRequirements(m_device, buffer->handle, &memRequirements); uint32_t memoryTypeIndex = find_memory_type(memRequirements.memoryTypeBits, properties); if (memoryTypeIndex == UINT32_MAX) { vkr = VK_ERROR_INITIALIZATION_FAILED; goto destroy_buffer; } { const VkMemoryAllocateInfo allocInfo = {VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO, nullptr, memRequirements.size, memoryTypeIndex}; vkr = vkAllocateMemory(m_device, &allocInfo, &g_bufferAllocCallbacks, &buffer->memory); if (vkr != VK_SUCCESS) { vkr = VK_ERROR_OUT_OF_DEVICE_MEMORY; goto destroy_buffer; } } vkr = vkBindBufferMemory(m_device, buffer->handle, buffer->memory, 0); if (vkr != VK_SUCCESS) { vkr = VK_ERROR_OUT_OF_DEVICE_MEMORY; goto free_memory; } buffer->size = size; m_buffers.push_back(*buffer); return vkr; free_memory: vkFreeMemory(m_device, buffer->memory, &g_bufferAllocCallbacks); buffer->memory = VK_NULL_HANDLE; destroy_buffer: vkDestroyBuffer(m_device, buffer->handle, &g_bufferAllocCallbacks); buffer->handle = VK_NULL_HANDLE; return vkr; }
VkResult vk_cleanup() { if (m_pipeline.handle != VK_NULL_HANDLE) vkDestroyPipeline(m_device, m_pipeline.handle, &g_bufferAllocCallbacks); if (m_pipeline.layout != VK_NULL_HANDLE) vkDestroyPipelineLayout(m_device, m_pipeline.layout, &g_bufferAllocCallbacks); if (m_framebuffer.handle != VK_NULL_HANDLE) vkDestroyFramebuffer(m_device, m_framebuffer.handle, &g_bufferAllocCallbacks); if (m_renderPass.handle != VK_NULL_HANDLE) vkDestroyRenderPass(m_device, m_renderPass.handle, &g_bufferAllocCallbacks); if (m_colorImage.handle != VK_NULL_HANDLE) vkDestroyImage(m_device, m_colorImage.handle, &g_imageAllocCallbacks); if (m_colorImage.memory != VK_NULL_HANDLE) vkFreeMemory(m_device, m_colorImage.memory, &g_imageAllocCallbacks); for (const vk_buffer &buf : m_buffers) { vkDestroyBuffer(m_device, buf.handle, &g_bufferAllocCallbacks); vkFreeMemory(m_device, buf.memory, &g_bufferAllocCallbacks); } m_buffers.clear(); if (m_device != VK_NULL_HANDLE) vkDestroyDevice(m_device, nullptr); if (m_devices != nullptr) free(m_devices); if (m_instance != VK_NULL_HANDLE) vkDestroyInstance(m_instance, nullptr); return VK_SUCCESS; }
void my_init_vulkan(void) { vk_device_init_count(&device_count); }
void my_create_image(void) { vk_create_image(800, 600, VK_FORMAT_R8G8B8A8_UNORM, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, &m_colorImage); vk_track_image(&m_colorImage, 800, 600, VK_FORMAT_R8G8B8A8_UNORM, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT); }
void my_create_shader_modules(VkShaderModule *vertShader, VkShaderModule *fragShader) { uint32_t tmp[] = {0x07230203}; std::vector<char> code((char*)tmp, (char*)(tmp + 1)); vk_create_shader_module(&code, vertShader); vk_create_shader_module(&code, fragShader); }
void my_create_render_pass(void) { vk_create_render_pass(VK_FORMAT_R8G8B8A8_UNORM, &m_renderPass); }
void my_create_framebuffer(void) { vk_create_framebuffer(&m_colorImage, &m_renderPass, &m_framebuffer); }
void my_create_pipeline(VkShaderModule vertShader, VkShaderModule fragShader) { vk_create_pipeline(vertShader, fragShader, &m_renderPass, &m_pipeline); }
void my_create_vertex_buffer(void) { float meshVertices[] = { -0.2f, -0.2f, 0.2f, -0.2f, 0.0f, 0.2f }; vk_buffer vertexBuffer; vk_create_buffer(sizeof(meshVertices), VK_BUFFER_USAGE_VERTEX_BUFFER_BIT, &vertexBuffer); vk_track_buffer(&vertexBuffer, sizeof(meshVertices), VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT); void *data; vkMapMemory(m_device, vertexBuffer.memory, 0, sizeof(meshVertices), 0, &data); memcpy(data, meshVertices, sizeof(meshVertices)); vkUnmapMemory(m_device, vertexBuffer.memory); std::cout << "Vertex buffer created.\n"; }
void my_record_and_submit_instanced_draw(void) { const VkCommandPoolCreateInfo poolInfo = {VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO, nullptr, 0, 0}; VkCommandPool commandPool; vkCreateCommandPool(m_device, &poolInfo, &g_bufferAllocCallbacks, &commandPool); const VkCommandBufferAllocateInfo allocInfo = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO, nullptr, commandPool, VK_COMMAND_BUFFER_LEVEL_PRIMARY, 1}; VkCommandBuffer commandBuffer; vkAllocateCommandBuffers(m_device, &allocInfo, &commandBuffer); const VkCommandBufferBeginInfo beginInfo = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO, nullptr, VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT, nullptr}; vkBeginCommandBuffer(commandBuffer, &beginInfo); const VkClearValue clearValue = {{0.0f, 0.0f, 0.0f, 1.0f}}; const VkRenderPassBeginInfo renderPassInfo = {VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO, nullptr, m_renderPass.handle, m_framebuffer.handle, {{0, 0}, {800, 600}}, 1, &clearValue}; vkCmdBeginRenderPass(commandBuffer, &renderPassInfo, VK_SUBPASS_CONTENTS_INLINE); vkCmdBindPipeline(commandBuffer, VK_PIPELINE_BIND_POINT_GRAPHICS, m_pipeline.handle); VkDeviceSize offset = 0; vkCmdBindVertexBuffers(commandBuffer, 0, 1, &m_buffers[0].handle, &offset); vkCmdDraw(commandBuffer, 3, 3, 0, 0); vkCmdEndRenderPass(commandBuffer); vkEndCommandBuffer(commandBuffer); const VkSubmitInfo submitInfo = {VK_STRUCTURE_TYPE_SUBMIT_INFO, nullptr, 0, nullptr, nullptr, 1, &commandBuffer, 0, nullptr}; vkQueueSubmit(m_queue, 1, &submitInfo, VK_NULL_HANDLE); vkQueueWaitIdle(m_queue); vkFreeCommandBuffers(m_device, commandPool, 1, &commandBuffer); vkDestroyCommandPool(m_device, commandPool, &g_bufferAllocCallbacks); std::cout << "Instanced draw (3 instances) submitted.\n"; }
